Repository INM-6/multi-area-model, pull requests merged in 2024-01, with the labels that each got.

#57 Reproducibility
  K_stable.npy
  README.md
  multiarea_model/default_params.py
  multiarea_model/multiarea_model.py
  multiarea_model/simulation.py
  run_example_downscaled.py
  run_example_fullscale.py
Labels: bug

#56 Color scheme interareal connectivity
  figures/MAM2EBRAINS/M2E_visualize_interareal_connectivity.py
  multi-area-model.ipynb
Labels: bug, enhancement, code improvement

#58 Instantaneous firing rate across all areas
  figures/MAM2EBRAINS/M2E_generate_data.py
  figures/MAM2EBRAINS/M2E_visualize_firing_rate.py
  figures/MAM2EBRAINS/M2E_visualize_interareal_connectivity.py
  figures/MAM2EBRAINS/M2E_visualize_resting_state.py
  multi-area-model.ipynb
Labels: enhancement, code improvement
